### ISSUE TITLE
checkpoint link broken

### ISSUE THREAD

**Issue by bengmstrong** [zhu-xlab/DINO-MM#2]
Hi! I'd love to experiment with your pretrained model for a project I'm working on. Unfortunately it seems like the [link to download the model weights]([checkpoint](https://smtaschool-my.sharepoint.com/:u:/g/personal/e3819_365e_live/EduwHbFkMe5JuCufw_97eRUBD-l9_8EzYbMETzTzCLUfzQ?e=gwcPve)) is broken (see screenshot below).

![image](https://github.com/zhu-xlab/DINO-MM/assets/108955227/8b04c56a-3cd6-40e2-a6cd-b1a4849ad80b)

**Comment by wangyi111** [comment]
Hi @bengmstrong, thanks for your notice! We've updated the weight link. Let me know if you have any further questions!
